version: '3.9'

services:
  cassandra:
    image: cassandra:3.11
    ports:
      - 9042:9042
    environment:
        - "MAX_HEAP_SIZE=256M"
        - "HEAP_NEWSIZE=128M"
        - CASSANDRA_CLUSTER_NAME=domins
    restart: always
    # volumes:
    #   - ./cassandra_data:/var/lib/cassandra
  #   healthcheck:
  #       test: ["CMD", "cqlsh", "-u cassandra", "-p cassandra" ,"-e describe keyspaces"]
  #       interval: 15s
  #       timeout: 10s
  #       retries: 10

  # cassandra-load-keyspace:
  #     container_name: cassandra-load-keyspace
  #     image: cassandra:3.11
  #     depends_on:
  #       cassandra:
  #         condition: service_healthy
  #     volumes:
  #       - ./schema.cql:/schema.cql
  #     command: /bin/bash -c "echo loading cassandra keyspace && cqlsh cassandra -f /schema.cql"